"""`memtara-prove` — the deployable device prover, end to end.

Two halves, deliberately separated:

  Offline    the vault file: what it refuses to load and why. No server, no
             toolchain, no Postgres. These run everywhere.

  Live       the actual journey — a real proof generated by the real Noir and
             Barretenberg toolchain, submitted to the real server, verified
             by real `bb verify`. Skips if any prerequisite is missing; CI
             fails the build if anything skipped (.github/workflows/ci.yml).

What this file is protecting is the claim on the tin: a bank can embed this
tool in an advisor terminal or a mobile app, and the client's four figures
never leave the device. So the tests assert on the *process boundary* — what
crosses the wire, what the exit code says, what the vault refuses — rather
than on the CLI's internals.

Run:
    DATABASE_URL=postgres://memtara:memtara@localhost:5433/memtara \\
    PATH="$HOME/.cargo/bin:$HOME/.bb:$HOME/.nargo/bin:$PATH" \\
    .venv/bin/python -m pytest tests/test_prover_cli.py -v
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import stat
import subprocess
import sys
import uuid
from pathlib import Path

import httpx
import pytest

from conftest import CLIENTS_DIR, REPO_ROOT, db_connect

import wealth_client as wc

PROVE = REPO_ROOT / "clients" / "prover" / "memtara-prove"

PRODUCT_ISIN = "XS1234567890"
PRODUCT_NAME = "5-Year S&P Principal Protected Note"
MIN_INCOME = 500_000
MIN_LIQUIDITY = 1_000_000
MAX_CONCENTRATION = 30
RISK_LEVEL = 3

SUITABLE = dict(income=750_000, liquid_assets=2_000_000, risk_tolerance=4, existing_holdings_value=200_000)
#: Same client, one limb short: a risk tolerance of 2 against a level-3
#: product. Everything else clears comfortably, so the decline is
#: unambiguously attributable to one limb.
DECLINED = dict(SUITABLE, risk_tolerance=2)

sys.path.insert(0, str(CLIENTS_DIR))
from prover import vault as vaultlib  # noqa: E402
from prover.cli import EXIT_NOT_SUITABLE  # noqa: E402


def _hash_token(token: str) -> str:
    return base64.urlsafe_b64encode(hashlib.sha256(token.encode()).digest()).decode().rstrip("=")


def _b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).decode().rstrip("=")


def run_cli(*args: str, expect: int | None = 0) -> subprocess.CompletedProcess:
    """Invoke the shim as a subprocess, the way a mobile app would.

    Not `main(argv)` in-process: the integration contract this tool sells is
    "spawn it and parse stdout", and an in-process call would not catch a
    stray `print` polluting the JSON, which is the failure that would actually
    break an embedder.
    """
    proc = subprocess.run(
        [sys.executable, str(PROVE), *args], capture_output=True, text=True, cwd=REPO_ROOT, timeout=300
    )
    if expect is not None and proc.returncode != expect:
        raise AssertionError(
            f"memtara-prove {' '.join(args)} exited {proc.returncode}, expected {expect}\n"
            f"--- stdout ---\n{proc.stdout}\n--- stderr ---\n{proc.stderr}"
        )
    return proc


# ---------------------------------------------------------------------------
# The vault file — offline
# ---------------------------------------------------------------------------


def test_init_vault_writes_an_owner_only_file_and_reports_the_public_key(tmp_path):
    path = tmp_path / "vault.json"
    proc = run_cli(
        "init-vault", "--vault-path", str(path),
        "--income", "750000", "--liquid-assets", "2000000",
        "--risk-tolerance", "4", "--existing-holdings-value", "200000",
    )

    assert stat.S_IMODE(path.stat().st_mode) == 0o600, (
        "the file holds plaintext figures and a signing key; it must be created 0600, not "
        "created world-readable and chmod'ed afterwards"
    )
    assert "public key" in proc.stdout.lower()

    document = json.loads(path.read_text())
    assert set(document["figures"]) == set(vaultlib.FIGURE_NAMES)
    # The seed, not the post-cofactor scalar. Storing the scalar would invite
    # a reader to rebuild the keypair without the factor of 8 `eddsa_verify`
    # applies, producing signatures that fail inside the circuit with no
    # diagnostic beyond "unsatisfied constraint".
    assert int(document["signing_key_seed"], 16) < wc.SUBORDER


def test_a_world_readable_vault_is_refused_not_warned_about(tmp_path):
    path = tmp_path / "vault.json"
    run_cli("init-vault", "--vault-path", str(path), "--income", "1", "--liquid-assets", "1", "--risk-tolerance", "3")
    path.chmod(0o644)

    with pytest.raises(vaultlib.VaultError) as exc:
        vaultlib.load(path)
    assert "readable beyond its owner" in str(exc.value)
    # An escape hatch has to exist for disposable test data, or the check
    # becomes something people work around by deleting it.
    assert vaultlib.load(path, allow_insecure_permissions=True).wealth.income == 1


def test_a_mistyped_figure_name_is_refused_rather_than_defaulted(tmp_path):
    """The failure mode this catches is invisible otherwise.

    A vault carrying `liquid_asets` would load with `liquid_assets` absent,
    prove against zero, fail the liquidity limb, and tell the holder they are
    unsuitable — with nothing anywhere pointing at the typo.
    """
    path = tmp_path / "vault.json"
    path.write_text(
        json.dumps(
            {
                "version": 1,
                "signing_key_seed": format(7, "064x"),
                "figures": {"income": 1, "liquid_asets": 1, "risk_tolerance": 3, "existing_holdings_value": 0},
            }
        )
    )
    path.chmod(0o600)
    with pytest.raises(vaultlib.VaultError) as exc:
        vaultlib.load(path)
    assert "liquid_asets" in str(exc.value)


def test_an_off_scale_risk_tolerance_is_refused_at_the_vault(tmp_path):
    with pytest.raises(vaultlib.VaultError) as exc:
        vaultlib.create(tmp_path / "v.json", income=1, liquid_assets=1, risk_tolerance=9, existing_holdings_value=0)
    assert "1 and 5" in str(exc.value)


def test_a_seeded_vault_is_reproducible_and_an_unseeded_one_is_not(tmp_path):
    a = vaultlib.create(tmp_path / "a.json", income=1, liquid_assets=1, risk_tolerance=3, existing_holdings_value=0, seed=42)
    b = vaultlib.create(tmp_path / "b.json", income=1, liquid_assets=1, risk_tolerance=3, existing_holdings_value=0, seed=42)
    c = vaultlib.create(tmp_path / "c.json", income=1, liquid_assets=1, risk_tolerance=3, existing_holdings_value=0)
    assert a.keypair.public == b.keypair.public, "--seed exists so a demo can reproduce a client exactly"
    assert c.keypair.public != a.keypair.public, "the default must be fresh randomness"


def test_the_cli_refuses_to_open_an_assessment_without_an_org_key(tmp_path):
    """The deployment distinction, enforced rather than documented.

    An org API key can open an assessment against any of the bank's users, so
    a holder's device must not have one — and the error has to point at the
    mode that device should be using instead, or whoever hits it will simply
    put the org key on the phone.
    """
    path = tmp_path / "vault.json"
    run_cli("init-vault", "--vault-path", str(path), "--income", "1", "--liquid-assets", "1", "--risk-tolerance", "3")
    proc = run_cli(
        "--vault-path", str(path), "--user-id", str(uuid.uuid4()), "--product-isin", PRODUCT_ISIN,
        expect=1,
    )
    combined = proc.stdout + proc.stderr
    assert "org API key" in combined
    assert "--request-id" in combined, "the error must name the mode a device should use"


def test_resuming_a_request_requires_the_matching_request_file(tmp_path):
    path = tmp_path / "vault.json"
    run_cli("init-vault", "--vault-path", str(path), "--income", "1", "--liquid-assets", "1", "--risk-tolerance", "3")

    request_file = tmp_path / "request.json"
    request_file.write_text(json.dumps({"request_id": str(uuid.uuid4())}))
    proc = run_cli(
        "--vault-path", str(path), "--request-id", str(uuid.uuid4()),
        "--request-file", str(request_file), "--session-token", "irrelevant",
        expect=1,
    )
    assert "does not match" in proc.stdout + proc.stderr


# ---------------------------------------------------------------------------
# The journey — live
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def desk(memtara_server: str):
    """A bank with one approved product, and a client whose vault root is
    registered — everything `memtara-prove` needs to exist on the server side
    before a device can prove anything."""
    reason = wc.missing_toolchain_reason()
    if reason:
        pytest.skip(f"cannot generate proofs here: {reason}")

    org = httpx.post(
        f"{memtara_server}/orgs",
        json={"name": f"Prover CLI Desk {uuid.uuid4().hex[:8]}", "org_type": "bank"},
        timeout=10.0,
    ).json()

    httpx.post(
        f"{memtara_server}/api/v1/products",
        json={
            "product_isin": PRODUCT_ISIN,
            "product_name": PRODUCT_NAME,
            "risk_level": RISK_LEVEL,
            "min_income": MIN_INCOME,
            "min_liquidity": MIN_LIQUIDITY,
            "max_concentration_percent": MAX_CONCENTRATION,
            "approved_by_risk_committee": True,
        },
        headers={"Authorization": f"Bearer {org['api_key']}"},
        timeout=10.0,
    ).raise_for_status()

    conn = db_connect()
    user_id = str(uuid.uuid4())
    session_token = f"prover-cli-{uuid.uuid4().hex}"
    conn.run(
        "insert into users (id, phone_e164) values (:id, :phone)",
        id=user_id,
        phone=f"+9715{uuid.uuid4().int % 10**8:08d}",
    )
    conn.run(
        "insert into sessions (user_id, token_hash, expires_at) values (:uid, :hash, now() + interval '1 hour')",
        uid=user_id,
        hash=_hash_token(session_token),
    )

    try:
        yield {
            "org_id": org["id"],
            "api_key": org["api_key"],
            "user_id": user_id,
            "session_token": session_token,
            "base_url": memtara_server,
            "conn": conn,
        }
    finally:
        for statement in (
            "delete from proofs where request_id in (select id from disclosure_requests where org_id = :oid)",
            "delete from audit_log where org_id = :oid",
            "delete from audit_log where ref_id in (select id from disclosure_requests where org_id = :oid)",
            "delete from wealth_requests where request_id in (select id from disclosure_requests where org_id = :oid)",
            "delete from used_nonces where org_id = :oid",
            "delete from disclosure_requests where org_id = :oid",
            "delete from products where org_id = :oid",
            "delete from organizations where id = :oid",
        ):
            try:
                conn.run(statement, oid=org["id"])
            except Exception:  # pragma: no cover
                pass
        for statement in (
            "delete from vault_blobs where user_id = :uid",
            "delete from sessions where user_id = :uid",
            "delete from users where id = :uid",
        ):
            try:
                conn.run(statement, uid=user_id)
            except Exception:  # pragma: no cover
                pass
        conn.close()


def _provision(tmp_path: Path, desk: dict, figures: dict) -> Path:
    """Create a vault and register its root, which is what a real onboarding
    does — the server pins `vault_root`, so a device that has not synced
    cannot prove anything at all."""
    path = tmp_path / "vault.json"
    run_cli(
        "init-vault", "--vault-path", str(path),
        "--user-id", desk["user_id"],
        "--income", str(figures["income"]),
        "--liquid-assets", str(figures["liquid_assets"]),
        "--risk-tolerance", str(figures["risk_tolerance"]),
        "--existing-holdings-value", str(figures["existing_holdings_value"]),
    )

    root = json.loads(run_cli("--json", "vault-root", "--vault-path", str(path)).stdout)["vault_root"]

    # The sync is a compare-and-swap, so the current version has to be read
    # first — this module provisions the same user more than once (a suitable
    # vault, then a declined one) and a blind `expected_version: 0` would only
    # work the first time.
    auth = {"Authorization": f"Bearer {desk['session_token']}"}
    existing = httpx.get(f"{desk['base_url']}/vault", headers=auth, timeout=10.0)
    version = existing.json()["version"] if existing.status_code == 200 else 0

    httpx.put(
        f"{desk['base_url']}/vault",
        json={
            "ciphertext": _b64url(b"ciphertext-the-server-cannot-read"),
            "vault_root": _b64url(bytes.fromhex(root[2:])),
            "expected_version": version,
        },
        headers=auth,
        timeout=10.0,
    ).raise_for_status()
    return path


def test_the_advisor_terminal_journey_produces_a_real_token(tmp_path, desk):
    """The brief's literal invocation, from an advisor terminal, against a
    live server. Everything here is real: nargo, bb, Postgres, Ed25519."""
    vault_path = _provision(tmp_path, desk, SUITABLE)

    proc = run_cli(
        "--json",
        "--base-url", desk["base_url"],
        "--user-id", desk["user_id"],
        "--product-isin", PRODUCT_ISIN,
        "--vault-path", str(vault_path),
        "--org-api-key", desk["api_key"],
        "--session-token", desk["session_token"],
        "--show-product",
    )
    result = json.loads(proc.stdout)

    assert result["suitable"] is True
    assert result["product_isin"] == PRODUCT_ISIN
    assert result["product_name"] == PRODUCT_NAME
    assert result["proof_token"].count(".") == 2, "a compact JWS"

    # The claim that matters: no figure crossed the process boundary.
    #
    # Only the three money figures are checked. `risk_tolerance` is a single
    # digit between 1 and 5, and a digit occurs by chance inside every UUID,
    # timestamp and base64 token in the output — asserting on it would be
    # asserting on a coincidence, and would fail or pass for reasons unrelated
    # to disclosure.
    for figure in (SUITABLE["income"], SUITABLE["liquid_assets"], SUITABLE["existing_holdings_value"]):
        assert str(figure) not in proc.stdout, f"{figure} appeared on stdout"
        assert str(figure) not in proc.stderr, f"{figure} appeared on stderr"

    # And the token really is Memtara's, validated the way a relying party
    # would — against the published JWKS, not against anything this test knows.
    from integrations.aihoots.memtara_claims import JwksCache, validate_proof_token

    jwks = JwksCache(f"{desk['base_url']}/.well-known/jwks.json")
    jwks.load()
    verified = validate_proof_token(result["proof_token"], jwks=jwks, expected_issuer=desk["base_url"])
    assert verified.suitable is True
    assert verified.product_isin == PRODUCT_ISIN


def test_a_decline_is_a_successful_run_with_its_own_exit_code(tmp_path, desk):
    """The case the whole design exists for.

    A tool that could only report approvals would be useless as evidence —
    DFSA COB obliges a firm to have assessed, not to have approved. So a
    decline gets its own exit code: it is an answer, not a failure, and an
    embedder must be able to tell the two apart — including from a usage
    error, which is why the code is 3 and not argparse's 2.
    """
    vault_path = _provision(tmp_path, desk, DECLINED)

    proc = run_cli(
        "--json",
        "--base-url", desk["base_url"],
        "--user-id", desk["user_id"],
        "--product-isin", PRODUCT_ISIN,
        "--vault-path", str(vault_path),
        "--org-api-key", desk["api_key"],
        "--session-token", desk["session_token"],
        expect=EXIT_NOT_SUITABLE,
    )
    result = json.loads(proc.stdout)
    assert result["suitable"] is False
    assert result["proof_token"], "a declined assessment still produces signed evidence"


def test_the_device_mode_needs_no_org_key_at_all(tmp_path, desk):
    """The shape a phone actually runs.

    The bank opens the assessment and pushes the response to the device. The
    device holds the holder's session token and nothing else — no credential
    that could open an assessment against anybody.
    """
    vault_path = _provision(tmp_path, desk, SUITABLE)

    request = wc.open_assessment(
        desk["base_url"], desk["api_key"], user_id=desk["user_id"], product_isin=PRODUCT_ISIN
    )
    request_file = tmp_path / "request.json"
    request_file.write_text(json.dumps(request))

    proc = run_cli(
        "--json",
        "--base-url", desk["base_url"],
        "--vault-path", str(vault_path),
        "--request-id", request["request_id"],
        "--request-file", str(request_file),
        "--session-token", desk["session_token"],
    )
    result = json.loads(proc.stdout)
    assert result["suitable"] is True
    assert result["request_id"] == request["request_id"]


def test_dry_run_generates_a_proof_without_burning_the_nonce(tmp_path, desk):
    """A device should be able to confirm it can prove at all without
    consuming an assessment — the nonce is single-use, so a "test the
    plumbing" run that spent one would be worse than useless."""
    vault_path = _provision(tmp_path, desk, SUITABLE)
    request = wc.open_assessment(
        desk["base_url"], desk["api_key"], user_id=desk["user_id"], product_isin=PRODUCT_ISIN
    )
    request_file = tmp_path / "request.json"
    request_file.write_text(json.dumps(request))

    dry = json.loads(
        run_cli(
            "--json", "--base-url", desk["base_url"], "--vault-path", str(vault_path),
            "--request-id", request["request_id"], "--request-file", str(request_file),
            "--session-token", desk["session_token"], "--dry-run",
        ).stdout
    )
    assert dry["dry_run"] is True
    assert len(dry["public_inputs"]) == 12

    # Still answerable afterwards.
    real = json.loads(
        run_cli(
            "--json", "--base-url", desk["base_url"], "--vault-path", str(vault_path),
            "--request-id", request["request_id"], "--request-file", str(request_file),
            "--session-token", desk["session_token"],
        ).stdout
    )
    assert real["suitable"] is True


def test_a_device_whose_vault_root_is_not_registered_cannot_prove(tmp_path, desk):
    """The Merkle limb proves the figures are in *a* tree. Only the server's
    pin makes it *this client's* tree — without it a device could build a
    tree to order."""
    unsynced = tmp_path / "unsynced.json"
    run_cli(
        "init-vault", "--vault-path", str(unsynced),
        "--income", "99000000", "--liquid-assets", "99000000",
        "--risk-tolerance", "5", "--existing-holdings-value", "0",
    )
    proc = run_cli(
        "--base-url", desk["base_url"],
        "--user-id", desk["user_id"],
        "--product-isin", PRODUCT_ISIN,
        "--vault-path", str(unsynced),
        "--org-api-key", desk["api_key"],
        "--session-token", desk["session_token"],
        expect=1,
    )
    assert "vault_root" in proc.stdout + proc.stderr
